version: "2"

services:
  namenode:
    build: ./namenode
    image: bde2020/hadoop-namenode
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "9870:9870"
  
  resourcemanager:
    build: ./resourcemanager
    image: bde2020/hadoop-resourcemanager
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864"
    env_file:
      - ./hadoop.env
    ports:
      - "8088:8088"
  
  historyserver:
    build: ./historyserver
    image: bde2020/hadoop-historyserver
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
      - datanode2
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
  
  nodemanager1:
    build: ./nodemanager
    image: bde2020/hadoop-nodemanager
    container_name: nodemanager1
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088"
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env
    
  datanode1:
    build: ./datanode
    image: bde2020/hadoop-datanode
    container_name: datanode1
    depends_on:
      - namenode
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
  
  datanode2:
    build: ./datanode
    image: bde2020/hadoop-datanode
    container_name: datanode2
    depends_on:
      - namenode
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
  
  datanode3:
    build: ./datanode
    image: bde2020/hadoop-datanode
    container_name: datanode3
    depends_on:
      - namenode
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_historyserver:
